[package]
name = "freshtrack-stylus"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"
stylus-sdk = "0.9.0"
hex = { version = "0.4", default-features = false }

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "freshtrack-stylus"
path = "src/main.rs"

# Fijamos ruint a 1.12.3 para evitar el bug de evaluación de constantes
# en ruint >= 1.13 cuando se usa Uint<8,1> (address/u8) en storage traits
[patch.crates-io]
ruint = { version = "=1.12.3", package = "ruint" }
